"""Add products table

Revision ID: 74e02b88b158
Revises: b8318bef8cb3
Create Date: 2025-12-06 11:17:56.106785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e02b88b158'
down_revision: Union[str, None] = 'b8318bef8cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.Enum('APPETIZERS', 'MAIN', 'PASTA', 'SEAFOOD', 'DESSERTS', 'BEVERAGES', 'POPULAR', 'VEGETABLES', 'FRUITS', 'DAIRY', 'BAKERY', 'MEAT', 'GROCERY', 'SAUCES', 'OILS', 'SNACKS', name='productcategory'), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('is_special', sa.Boolean(), nullable=True),
    sa.Column('is_offer', sa.Boolean(), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_is_offer'), 'products', ['is_offer'], unique=False)
    op.create_index(op.f('ix_products_is_popular'), 'products', ['is_popular'], unique=False)
    op.create_index(op.f('ix_products_is_special'), 'products', ['is_special'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_special'), table_name='products')
    op.drop_index(op.f('ix_products_is_popular'), table_name='products')
    op.drop_index(op.f('ix_products_is_offer'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
