"""Add SKU and ecommerce fields to products

Revision ID: 63a437be660b
Revises: 74e02b88b158
Create Date: 2025-12-06 11:26:47.467785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a437be660b'
down_revision: Union[str, None] = '74e02b88b158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.String(length=50), nullable=False))
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('tags', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'rating')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###
