"""update_productcategory_enum

Revision ID: 073fcca985f6
Revises: 3e6e7b33c58d
Create Date: 2025-12-23 18:08:30.767133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073fcca985f6'
down_revision: Union[str, None] = '3e6e7b33c58d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
